# Latent Diffusion Model Configuration for fMRI Image Reconstruction

# Data Configuration
data:
  data_path: "outputs"
  aligned_data_file: "alignment_ridge_20250527_070315_aligned_data.npz"
  num_subjects: 3
  num_timepoints: 27
  num_voxels: 3092
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

# VAE Configuration
vae:
  input_dim: 3092
  latent_dim: 256
  hidden_dims: [1024, 512, 256]
  beta: 1.0  # KL divergence weight
  learning_rate: 1e-4

# Diffusion Model Configuration
diffusion:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: "linear"  # linear, cosine, or quadratic
  model_channels: 128
  num_res_blocks: 2
  attention_resolutions: [16, 8]
  dropout: 0.1
  learning_rate: 1e-4

# Training Configuration
training:
  batch_size: 8
  num_epochs: 100
  gradient_accumulation_steps: 1
  mixed_precision: true
  save_every: 10
  eval_every: 5
  early_stopping_patience: 20
  checkpoint_dir: "checkpoints"
  log_dir: "logs"

# Sampling Configuration
sampling:
  num_inference_steps: 50
  guidance_scale: 7.5
  eta: 0.0

# Logging Configuration
logging:
  use_wandb: false
  project_name: "fmri_latent_diffusion"
  experiment_name: "baseline"
  log_every: 10

# Hardware Configuration
hardware:
  device: "auto"  # auto, cpu, cuda
  num_workers: 4
  pin_memory: true
