[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brain-ldm-uncertainty"
version = "1.0.0"
description = "Multi-Modal Brain Latent Diffusion Model with Monte Carlo Uncertainty Quantification"
readme = "README_JOURNAL.md"
license = {text = "MIT"}
authors = [
    {name = "Research Team", email = "research@institution.edu"}
]
maintainers = [
    {name = "Research Team", email = "research@institution.edu"}
]
keywords = [
    "brain-computer-interface",
    "fmri",
    "diffusion-models", 
    "uncertainty-quantification",
    "monte-carlo",
    "neuroscience",
    "deep-learning",
    "pytorch"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Scientific/Engineering :: Image Processing"
]
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
    "torchvision>=0.15.0", 
    "numpy>=1.21.0",
    "scipy>=1.7.0",
    "matplotlib>=3.5.0",
    "seaborn>=0.11.0",
    "scikit-learn>=1.0.0",
    "tqdm>=4.62.0",
    "PyYAML>=6.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0.0",
    "pytest-cov>=2.12.0",
    "black>=21.0.0",
    "flake8>=3.9.0",
    "isort>=5.9.0",
    "pre-commit>=2.15.0"
]
docs = [
    "sphinx>=4.0.0",
    "sphinx-rtd-theme>=1.0.0",
    "myst-parser>=0.15.0"
]
notebooks = [
    "jupyter>=1.0.0",
    "ipykernel>=6.0.0",
    "notebook>=6.4.0",
    "ipywidgets>=7.6.0"
]
all = [
    "brain-ldm-uncertainty[dev,docs,notebooks]"
]

[project.urls]
Homepage = "https://github.com/[username]/Brain-LDM-Uncertainty"
Documentation = "https://[username].github.io/Brain-LDM-Uncertainty/"
Repository = "https://github.com/[username]/Brain-LDM-Uncertainty.git"
Issues = "https://github.com/[username]/Brain-LDM-Uncertainty/issues"

[project.scripts]
brain-ldm-train = "src.training.train_improved_model:main"
brain-ldm-eval = "src.evaluation.uncertainty_evaluation:main"
brain-ldm-viz = "src.utils.visualization:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
exclude = ["tests*"]

[tool.setuptools.package-data]
"*" = ["*.yaml", "*.yml", "*.json", "*.txt", "*.md"]

# Black configuration
[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'

# isort configuration
[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["src"]
known_third_party = ["torch", "numpy", "scipy", "matplotlib", "seaborn", "sklearn", "tqdm", "yaml"]

# pytest configuration
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--verbose",
    "--cov=src",
    "--cov-report=term-missing"
]
markers = [
    "slow: marks tests as slow",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests"
]
